# Generated by Django 6.0.4 on 2026-04-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycsubmission",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("more_info_requested", "More Info Requested"),
                ],
                db_index=True,
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="submitted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
