# Generated by Django 6.0.4 on 2026-04-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KYCSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personal_name", models.CharField(blank=True, max_length=255)),
                ("personal_email", models.EmailField(blank=True, max_length=254)),
                ("personal_phone", models.CharField(blank=True, max_length=20)),
                ("business_name", models.CharField(blank=True, max_length=255)),
                (
                    "business_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("freelancer", "Freelancer"),
                            ("agency", "Agency"),
                            ("ecommerce", "Ecommerce"),
                            ("saas", "SaaS"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "expected_monthly_volume_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "pan_document",
                    models.FileField(blank=True, null=True, upload_to="kyc_documents/"),
                ),
                (
                    "aadhaar_document",
                    models.FileField(blank=True, null=True, upload_to="kyc_documents/"),
                ),
                (
                    "bank_statement_document",
                    models.FileField(blank=True, null=True, upload_to="kyc_documents/"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("more_info_requested", "More Info Requested"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("reviewer_reason", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
